version: "2"
services:
    jupyter:
        image: registry.cn-beijing.aliyuncs.com/fivecakes/jupyter
        cpus: 0.8
        mem_limit: "1g"
        ports:
            - "8888:8888"       #jupyterlab
            - "5000:5000"       #flask
        volumes:
            - /workspace/jupyter/:/jupyter
            - /workspace/deploy/:/deploy    
            - /workspace/repository/:/repository
            - /workspace/etc/jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py