version: "3"
services:
    jupyter:
        image: ${REGISTRY}/fivecakes/jupyter
        ports:
            - "8888:8888"       #jupyterlab
            - "5000:5000"       #flask
        volumes:
            - ${WORK_PATH}/jupyter/:/jupyter
            - ${WORK_PATH}/deploy/:/deploy    
            - ${WORK_PATH}/repository/:/repository
            - ${WORK_PATH}/etc/jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
        deploy:
          resources:
            limits:
              cpus: '0.8'
              memory: '1g'