version: "3"
services:
    jupyter:
        image: registry.cn-beijing.aliyuncs.com/fivecakes/jupyter
        ports:
            - "8888:8888"       #jupyterlab
            - "5000:5000"       #flask
        volumes:
            - /workspace/jupyter/:/jupyter
            - /workspace/deploy/:/deploy    
            - /workspace/repository/:/repository
            - /workspace/etc/jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
        deploy:
          resources:
            limits:
              cpus: '0.8'
              memory: '1g'