version: "3"

# 服务端使用的端口号：0～1023为熟知端口号,1024～49151为登记端口号
# 客户端使用的端口号：49152～65535
services:
    nginx:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/nginx
        ports:
            - "80:80"       #http
            - "443:443"     #https
        volumes:
            - /workspace:/workspace
    php:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/php
        volumes:
            - /workspace:/workspace
        ports:
            - "5678:5678"   #为git提供ssh
    mongodb:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/mongodb
        volumes:
            - /workspace/:/workspace
    mongodb_demo:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/mongodb_demo
        volumes:
            - /workspace/:/workspace
    redis:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/redis
        volumes:
            - /workspace/:/workspace
    nodejs:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/nodejs
        #ports:
        #    - "6789:6789"       #math
        volumes:
            - /workspace/deploy:/deploy

          
