version: "3"

# 服务端使用的端口号：0～1023为熟知端口号,1024～49151为登记端口号
# 客户端使用的端口号：49152～65535
services:
    nginx:
        image: ${REGISTRY}/fivecakes/nginx
        ports:
            - "80:80"       #http
            - "443:443"     #https
        volumes:
            - ${WORK_PATH}:/workspace
    php:
        image: ${REGISTRY}/fivecakes/php
        volumes:
            - ${WORK_PATH}:/workspace
        ports:
            - "5678:22"   #为git提供ssh
    mongodb:
        image: ${REGISTRY}/fivecakes/mongodb
        volumes:
            - ${WORK_PATH}:/workspace
    mongodb_demo:
        image: ${REGISTRY}/fivecakes/mongodb_demo
        volumes:
            - ${WORK_PATH}:/workspace
    redis:
        image: ${REGISTRY}/fivecakes/redis
        volumes:
            - ${WORK_PATH}:/workspace
    nodejs:
        image: ${REGISTRY}/fivecakes/nodejs
        volumes:
            - ${WORK_PATH}/deploy:/deploy
    janus:
        #network_mode: host
        image: ${REGISTRY}/fivecakes/janus
        volumes:
            - ${WORK_PATH}/etc/janus/janus.jcfg:/opt/janus/etc/janus/janus.jcfg

          
