version: "3"
services:
    spider:
        image: ${REGISTRY}/fivecakes/spider
        volumes:
            - ${WORK_PATH}/deploy/:/deploy
        deploy:
          resources:
            limits:
              cpus: '0.8'
              memory: '1g'