version: "3"
services:
    spider:
        image: registry-vpc.cn-beijing.aliyuncs.com/fivecakes/spider
        volumes:
            - /workspace/deploy/:/deploy
        deploy:
          resources:
            limits:
              cpus: '0.8'
              memory: '1g'