name: cling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyterlab
  - xeus-cling
  - pip
  - pip
    - Flask
    - tornado
    - scikit-learn
    - requests
    - matplotlib 
    - Pillow 
    - seaborn 
    - opencv-python 
    - hmmlearn 
    - tqdm 
    - imageio 
    - scikit-image 
    - pydub 
    - keras 
    - tensorflow
    - beautifulsoup4
    - html5lib
    - lxml